---
apiVersion: v1
kind: Secret
metadata:
  name: ha-toleration-test-tls
type: kubernetes.io/tls
data:
  # values are base64 encoded, which obscures them but does NOT provide
  # any useful level of confidentiality
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrVENDQWVHZ0F3SUJBZ0lVZUQ5OEZUakloV0tGVUs0VWgzbWpMRDJUOGlrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0RERUtNQWdHQTFVRUF3d0JLakFlRncweU5EQXpNVEF4TmpJeE1UbGFGdzB5TlRBek1UQXhOakl4TVRsYQpNQXd4Q2pBSUJnTlZCQU1NQVNvd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURCClpiRElyUEt2STJsN3Z6QXFWQXlLTjJybFVSOHd6cG11cHdrWFdZNHRTS1hRK2VPMHBaYnBMY0N3WDRRZlRuZlcKVkxlUElJbnBOcVIzbGxNSloxNmdZbXVrbUdMeTJ0MnpQS1JOM1U2eWNQSHRCM2NVUkZEbjZ1YTlxOGRxcXN6SQpyMmdDaDM0UTlwM1lxeVA0T2FWQVI2b3FaVCszNnA3VGZSUlFTUWdYRDI5RWJyZnI5SUd6M0dTSmtFTjhsNExVCmQ0Ym5ZdGhjNGhvVytsQ0l1TUJpNlRxRitGZ2g5Z3VoNTJVSjFVLy80YkcvN0Y1dDFMZklON21mUnBTQXRSUlcKbHp2TWZMOW4wVyttNHlXQy9EeExnVjkvUXRhQUxnR1ZaVmpYRUF2VkprQk9kUS8yMUNSMDZSZXVaSjcrVExXSgpPS01INVdpQ0c5Z3F1d0lRaGY5akFnTUJBQUdqVXpCUk1CMEdBMVVkRGdRV0JCVEkyN3VJVndkTzVUQnFVNTBMClNyUmM2T291QnpBZkJnTlZIU01FR0RBV2dCVEkyN3VJVndkTzVUQnFVNTBMU3JSYzZPb3VCekFQQmdOVkhSTUIKQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCTXN0Y0xCL2Q2dXI4U3pTL0xCTWMxTDdoKwpZOURvK25ialh0dTIwZkxBK2FCVVhFSFAyVytBalYyZG1jaFA3d2MrQVZYYWxLLy9EaTBrSGhSdWNIRXBSVXJPCm1iTWNtcDRZK1VRUS9jTTJUVGZKZ1E3MTBDRjlhdTBZeW8weWxuMzNiRE5jWDZjSnJKZUxaWEd6TmxIb2R4WVcKWHlMUTFHSTlDZVJCYjVMYVJQQ0IyZFpkU1N6Sko1MWJYR3VKdXpFWHFKM1pUWkN6ZVo3Q0dsanZUd1d0OGlnSwpZd0Y5NHlyYzEzYkNmK2ZZOEdDbloybG1pOThueVd6WDE0eXNETDhuQUVVano0ZE5pUDdsNUx4R1JVTDNjb2RjCjk1a0MyRGd3SEIxVE5tRW5JMFNWUGk0N21RRk5PZ0JNZFdPVnQ5Z2ZXRDRyODA4K0YvMGxmUXNndTExMgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  # This is an example, remember to not use in production
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRREJaYkRJclBLdkkybDcKdnpBcVZBeUtOMnJsVVI4d3pwbXVwd2tYV1k0dFNLWFErZU8wcFpicExjQ3dYNFFmVG5mV1ZMZVBJSW5wTnFSMwpsbE1KWjE2Z1ltdWttR0x5MnQyelBLUk4zVTZ5Y1BIdEIzY1VSRkRuNnVhOXE4ZHFxc3pJcjJnQ2gzNFE5cDNZCnF5UDRPYVZBUjZvcVpUKzM2cDdUZlJSUVNRZ1hEMjlFYnJmcjlJR3ozR1NKa0VOOGw0TFVkNGJuWXRoYzRob1cKK2xDSXVNQmk2VHFGK0ZnaDlndWg1MlVKMVUvLzRiRy83RjV0MUxmSU43bWZScFNBdFJSV2x6dk1mTDluMFcrbQo0eVdDL0R4TGdWOS9RdGFBTGdHVlpWalhFQXZWSmtCT2RRLzIxQ1IwNlJldVpKNytUTFdKT0tNSDVXaUNHOWdxCnV3SVFoZjlqQWdNQkFBRUNnZ0VBUnF0dUtpWm9sKzhNd0pkZ2RsYzRMZG1LU2ptV2VETkduVGVVYnQvZXdGVm4Kb2pGdUw3akNxSHA3aXZlY1JBUmNiZ21PK2RJZUV3WlFteEpuVFd4a2U1NzdUcTRRbWtXMzlhTVhOd3pEa1JrTQpqbHpIK3JQc0RKTWR0ZmxyYVdMNGFlME95TDNTSjBpMjdWRzhWeHhaY2wrOW9yaFV6RlFEcmF4ckc5dFVCWGlQCkI5QkovTjV1d3VvODFHbytoOXNlUVVaOE0xS1c4cCtKb2U4Yk5Vb2lOaEJZSGd5VFZPeVVRd2MwazQ5ZTU2elgKZjFHY0Q2SzNhNmNKdktRVjBVRUJpR2tPOFFPbVV1MWRVSWNHOXUyNVkyMUkydUovQzB2aWg4YWF1Y3dObzR2Uwo2WkFWZjBhNG5WdGNiYW1YRXg1Wnl3QVQyTXhQQ0ltTUVXWnROYklXWVFLQmdRRDAxcmlzNm5TVDZtUEZuKy82CjdZcEdZc1pYbUNlQWR0WXQxbnAydkg1cjVzR1ROY0JnM1d0aHMyanI0QXlweGlLWGo2UmpYb1ExTUdIc0l4VW0KY0xtK01LYmxvSm52SEphaHE3dXZhZGdla3dsamF2UjRnQmF3WTdNMjF4bUJaa0N3QUVFR0lhSnNVOVVBNHVXSQp3N3RONWVhaHNKT0JaNUtMaE1BV05nWlNYd0tCZ1FES05xVDJlQkVaeFp5MlcrNkFZVWdYMW9LN2Yzb3MzcXBYCjUzZDFMazJwbmQxYmVic0NKOFA5eVcxcW8yUlBRMm10bEFiZGFoQVUrY1U5YnJSVktZV01Ma3E4bWIvdDJ4TksKM0YwaE16ZUdndWZNR2dBQzhsV0RMdkoxZGpTaUlFb2JlT05HcjZZeVlKT0pGR0VsdmlwNU1wWTMrbWI4SWRlSwozOWwvbGV1WmZRS0JnQmNWZzVYeUNRbkZLS0VDWWxyek9IMUlaTkR2YkpJRklrNXlFVnZPaTlEYWtkZXlVckFQClVFZUc1ZGFQYWtJN2h4bHBGcU96enAxQk1ZcFZDSEoyWUZ6Wk0zTWxBRDUySUpHZm9uTjRkRUwxdEFYbW1LUWYKMTRQTDhxS3lCeHFYTEhRcm9mWFZCLzVVclJtSFN3THBDV2pmeXkzbGV4TFJWQlRKY0Y3bnV4TGJBb0dBVlNRUQo3UjI4eFljbzVyZHFnbTl6ZFdZQ2dZTzVJMjlWZGRHbHdKY1FhQnhwK1h3VnUyQ1c2eUtHaVdIbWVHRS8rNi9aCi9Cd09UV2FsSDZxZkQwUitVSG1sU2lmS1loSGQyNlZSS1F0eGs1ZEdsZTlVbGVrSERFY1dHMUw3OGs5NkpIc1AKNXRGS1B1ZmU5dGEzMkxackY4Q3U4ejdoWWNPMkIya2RJTlUwNzlrQ2dZQVVlTGVpWXNrdnJpSWlpVUd1d1JGawp0OGI1V0JVYmxxdXBPT080SGcxNEIyS3piVUkrRUJxZDFQWDVSQWxjYUFhYnNuVUhha1hpNCtvc0w5VkFzRkU1CjJZMG9RdzRWeHBZMy8zcVN6cTk2WHRiWWk4YXZJOTUxRWNtNUpHVjRkQUp1ZWxVN1NqY0cvQVB5dWFCLzM4OG0KSTdRbWVIaU5LcTJEdXZvejlleUVkUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: pubsubplus.solace.com/v1beta1
kind: PubSubPlusEventBroker
metadata:
  name: ha-toleration-test
spec:
  redundancy: true
  timezone: UTC
  podDisruptionBudgetForHA: true
  podLabels:
    "DeploymentType": "HA"
    "DeploymentTestMode": "TaintsAndToleration"
  podAnnotations:
    "DeploymentType": "HA"
    "DeploymentTestMode": "TaintsAndToleration"
  nodeAssignment:
    # make sure one node is tainted as node=primary to ensure only primary pubsubplusbroker node gets scheduled on node
    - name: Primary
      spec:
        tolerations:
        - effect: NoSchedule
          key: node
          operator: Equal
          value: primary
    # make sure one node is tainted as node=backup to ensure only primary pubsubplusbroker node gets scheduled on node
    - name: Backup
      spec:
        tolerations:
        - effect: NoSchedule
          key: node
          operator: Equal
          value: backup
    # make sure one node is tainted as node=monitor to ensure only primary pubsubplusbroker node gets scheduled on node
    - name: Monitor
      spec:
        tolerations:
        - effect: NoSchedule
          key: node
          operator: Equal
          value: monitor
  tls:
    enabled: true
    serverTlsConfigSecret: ha-toleration-test-tls
  service:
    type: LoadBalancer
  monitoring:
    enabled: true
    image:
      repository: ghcr.io/solacedev/pubsubplus-prometheus-exporter
      pullPolicy: Always
